"""
Django settings for gymmm project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
import dj_database_url
from corsheaders.defaults import default_headers

# Load .env locally (Railway uses Variables, this won't hurt)
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# Core security / env
# =========================
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key-change-me")

# IMPORTANT: do NOT hardcode DEBUG
DEBUG = os.getenv("DEBUG", "0") == "1"

# Railway gives you a public domain; easiest beginner-safe is allow all.
# Later tighten this to your domain(s).
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# =========================
# Razorpay env
# =========================
TEST_API_KEY_ID = os.getenv("TEST_API_KEY_ID", "")
TEST_KEY_SECRET = os.getenv("TEST_KEY_SECRET", "")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET", "")

# =========================
# Apps
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # third-party
    "rest_framework_simplejwt",
    "corsheaders",

    # local apps
    "users",
    "gym",
    "members",
    "billing",
]

# =========================
# Middleware (order matters)
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # right after SecurityMiddleware
    "corsheaders.middleware.CorsMiddleware",       # CORS early

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "gymmm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gymmm.wsgi.application"

# =========================
# Database (Railway)
# =========================
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Railway/Postgres - force SSL (beginner safe)
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Local dev fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =========================
# Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# Internationalization
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =========================
# Static files (WhiteNoise)
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# This is fine with WhiteNoise in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# =========================
# Auth user model
# =========================
AUTH_USER_MODEL = "users.User"

# =========================
# DRF / JWT
# =========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# =========================
# CORS (React/Vite + production)
# =========================
CORS_ALLOW_HEADERS = list(default_headers) + ["authorization"]

# IMPORTANT:
# - Don't put "*" inside CORS_ALLOWED_ORIGINS (invalid)
# - Use allow-all only while testing
# If you want "everything allowed" temporarily:
#CORS_ALLOW_ALL_ORIGINS = True

# If you want strict mode later, do this instead:
# CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
     "http://localhost:5173",
     "http://127.0.0.1:5173",
     "https://gymsaasdhyan.netlify.app",
 ]

CORS_ALLOW_CREDENTIALS = True
